- name: Install required packages
  pacman:
    name:
      - base-devel  # Arch equivalent of build-essential, includes gcc, make, etc.
      - curl
      - git
      - zsh
      - stow
      - tmux
      - fortune-mod  # Arch package name for fortune
      - cowsay
      - exa
    state: present
    update_cache: yes  # Equivalent to apt-get update
  become: true  # Run as root

- name: Clone stow repo
  git:
    repo: https://github.com/Ashish-Github193/Gnu-stow-repo.git
    dest: /home/x/Projects/Gnu-stow-repo
    depth: 1  # Shallow clone, like --depth 1
  become: yes
  become_user: x  # Run as user x

- name: Add git config symlink
  command:
    cmd: stow -t ~ git
    chdir: /home/x/Projects/Gnu-stow-repo
  become: yes
  become_user: x  # Run as user x

- name: Add tmux config symlink
  command:
    cmd: stow -t ~ tmux
    chdir: /home/x/Projects/Gnu-stow-repo
  become: yes
  become_user: x  # Run as user x
