- name: Install fzf in container as user x
  community.docker.docker_container_exec:
    container: dev_container
    command: bash -c "git clone --depth 1 https://github.com/junegunn/fzf.git /home/x/.fzf && /home/x/.fzf/install --all"
    user: x

- name: Verify fzf is installed and accessible
  community.docker.docker_container_exec:
    container: dev_container
    command: bash -c "~/.fzf/bin/fzf --version"
    user: x
  register: fzf_version
- debug:
    msg: "fzf version: {{ fzf_version.stdout }}"
