- name: Install Neovim in container
  community.docker.docker_container_exec:
    container: my_setup_container
    command: bash -c "curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz && tar -C /opt -xzf nvim-linux-x86_64.tar.gz && rm nvim-linux-x86_64.tar.gz && ln -s /opt/nvim-linux-x86_64/bin/nvim /usr/local/bin/nvim"
    user: root

- name: Install Packer.nvim in container as user x
  community.docker.docker_container_exec:
    container: my_setup_container
    command: bash -c "git clone --depth 1 https://github.com/wbthomason/packer.nvim /home/x/.local/share/nvim/site/pack/packer/start/packer.nvim"
    user: x

- name: Add Neovim config to container
  community.docker.docker_container_exec:
    container: my_setup_container
    command: bash -c "git clone --depth 1 https://github.com/Ashish-Github193/Gnu-stow-repo.git /home/x/Projects/Gnu-stow-repo"
    user: x

- name: Add Neovim config symlink
  community.docker.docker_container_exec:
    container: my_setup_container
    command: bash -c "cd /home/x/Projects/Gnu-stow-repo && stow -t ~ nvim"
    user: x

