- name: Install required packages in container
  community.docker.docker_container_exec:
    container: dev_container
    command: |
      bash -c "apt-get update && 
               apt-get install -y build-essential \
                                  curl \
                                  git \
                                  make \
                                  gcc \
                                  zsh \
                                  stow \
                                  tmux \
                                  fortune \
                                  cowsay \
                                  exa && 
               apt-get clean"
    user: root

- name: Add stow repo to container
  community.docker.docker_container_exec:
    container: dev_container
    command: bash -c "git clone --depth 1 https://github.com/Ashish-Github193/Gnu-stow-repo.git /home/x/Projects/Gnu-stow-repo"
    user: x

- name: Add git config symlink
  community.docker.docker_container_exec:
    container: dev_container
    command: bash -c "cd /home/x/Projects/Gnu-stow-repo && stow -t ~ git"
    user: x

- name: Add tmux config symlink
  community.docker.docker_container_exec:
    container: dev_container
    command: bash -c "cd /home/x/Projects/Gnu-stow-repo && stow -t ~ tmux"
    user: x

