- name: Copy Dockerfile to project directory
  ansible.builtin.copy:
    content: |
      FROM ubuntu:22.04
      ENV DEBIAN_FRONTEND=noninteractive
      RUN apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*
      ARG USERNAME=x
      ARG PASSWORD=x
      RUN useradd -m -s /bin/bash ${USERNAME} && echo "${USERNAME}:${PASSWORD}" | chpasswd && usermod -aG sudo ${USERNAME}
      WORKDIR /home/${USERNAME}
      CMD ["sleep", "infinity"]
    dest: "{{ playbook_dir }}/Dockerfile"
    mode: '0644'

- name: Build Docker image
  ansible.builtin.docker_image:
    name: custom_ubuntu_setup
    tag: latest
    source: build
    build:
      path: "{{ playbook_dir }}"
    state: present

